export type UiColorTuple = readonly [number, number, number, number?];

export const UI_SKIN = {
    version: 1,
    assets: {
        titleBanner: 'ui/shared/banners/title_banner_blank',
        panelMain: 'ui/shared/panels/panel_main',
        panelDialog: 'ui/shared/panels/panel_dialog',
        panelList: 'ui/shared/panels/panel_list',
        panelChip: 'ui/shared/panels/panel_chip',
        buttonPrimary: 'ui/shared/buttons/button_primary_idle',
        buttonPrimaryPressed: 'ui/shared/buttons/button_primary_pressed',
        buttonSecondary: 'ui/shared/buttons/button_secondary_idle',
        buttonBack: 'ui/shared/buttons/button_back_idle',
        buttonDanger: 'ui/shared/buttons/button_danger_idle',
        buttonDisabled: 'ui/shared/buttons/button_disabled',
        buttonCompact: 'ui/shared/buttons/button_compact_idle',
        levelCard: 'ui/shared/cards/level_card_idle',
        levelCardSelected: 'ui/shared/cards/level_card_selected',
        levelCardLocked: 'ui/shared/cards/level_card_locked',
        primateCard: 'ui/shared/cards/primate_card_idle',
        primateCardSelected: 'ui/shared/cards/primate_card_selected',
        achievementCard: 'ui/shared/cards/achievement_card',
        achievementCardLocked: 'ui/shared/cards/achievement_card_locked',
        emptyStateCard: 'ui/shared/cards/empty_state_card',
        sliderTrack: 'ui/shared/controls/slider_track',
        sliderFill: 'ui/shared/controls/slider_fill',
        sliderKnob: 'ui/shared/controls/slider_knob',
        toggleOn: 'ui/shared/controls/toggle_on',
        toggleOff: 'ui/shared/controls/toggle_off',
        hudPanel: 'ui/shared/cards/hud_panel',
        hudControl: 'ui/shared/cards/hud_control',
        statusChip: 'ui/shared/cards/status_chip',
        buttonLabelPlate: 'objectives/ui/ui_label_plate_01',
    },
    typography: {
        title: { size: 38, color: [255, 226, 122, 255] as UiColorTuple, outline: [48, 28, 12, 255] as UiColorTuple, outlineWidth: 3 },
        button: { size: 20, color: [255, 244, 204, 255] as UiColorTuple, outline: [42, 24, 10, 255] as UiColorTuple, outlineWidth: 2 },
        body: { size: 18, color: [246, 236, 204, 255] as UiColorTuple, outline: [30, 21, 14, 235] as UiColorTuple, outlineWidth: 1 },
        caption: { size: 13, color: [224, 219, 188, 255] as UiColorTuple, outline: [24, 18, 12, 220] as UiColorTuple, outlineWidth: 1 },
        accent: { size: 18, color: [255, 226, 122, 255] as UiColorTuple, outline: [42, 24, 10, 255] as UiColorTuple, outlineWidth: 2 },
    },
    colors: {
        overlay: [22, 17, 12, 154] as UiColorTuple,
        overlayStrong: [22, 17, 12, 210] as UiColorTuple,
        text: [246, 236, 204, 255] as UiColorTuple,
        muted: [198, 195, 174, 255] as UiColorTuple,
        accent: [255, 220, 105, 255] as UiColorTuple,
        success: [154, 231, 136, 255] as UiColorTuple,
        danger: [255, 145, 112, 255] as UiColorTuple,
        info: [135, 207, 241, 255] as UiColorTuple,
    },
    spacing: {
        xs: 8,
        sm: 12,
        md: 18,
        lg: 28,
        xl: 40,
    },
} as const;

export const UI_SHARED_ASSET_KEYS: readonly string[] = Array.from(new Set(Object.values(UI_SKIN.assets)));

export const UI_SCREEN_TITLES: Readonly<Record<string, string>> = {
    menu: 'МАРТЫШКИН ТРУД',
    name: 'НАЧАТЬ ИГРУ',
    sound: 'ЗВУК И НАСТРОЙКИ',
    records: 'МАРТЫШКИНЫ РЕКОРДЫ',
    achievements: 'МАРТЫШКИНЫ ДОСТИЖЕНИЯ',
    paused: 'ПЕРЕРЫВ НА БАНАН',
    clear: 'УРОВЕНЬ ПРОЙДЕН',
    over: 'МАРТЫШКА УПАЛА',
    finished: 'ПРОЕКТ УСПЕШЕН',
    skins: 'ВЫБЕРИ СВОЕГО ПРИМАТА',
    levels: 'ВЫБОР УРОВНЯ',
    devgate: 'ДОСТУП РАЗРАБОТЧИКА',
    devpanel: 'МАРТЫШКИН ПУЛЬТ',
};
